services:
  postgres:
    container_name: "fesmu-db"
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${SERVER_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
